### ISSUE TITLE
compile 失败....

### ISSUE THREAD

**Issue by newamber** [unixzii/android-SpringAnimator#2]
Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.

**Comment by unixzii** [comment]
Could you elaborate on that? Is this your own project or the sample project?

**Comment by newamber** [comment]
It's my own project,  I followed the usage to compile it in my build.gradle(app) and then the error happened.

**Comment by unixzii** [comment]
@Newamber
Sorry to make you keep waiting for this. I've just figured out what caused this error, and now it's already fixed. You could try cleaning your project and rebuild it again.

Thanks for your feedback.
